% Make NetCDF forcing
%
% Create forcing input file
% Written by Dongyue Li
% Revised 9/25/2019 JRS
%
% Should add ability to write out one file per year, since that is how the
% image driver expects to receive forcing input data

function make_netcdf_forcing(indir, outname)

% indir = '/Volumes/HD4/SWOTDA/Data/Tuolumne/forc_nc';
% outname = '/Volumes/HD4/SWOTDA/Data/Tuolumne/forc_image_2.nc';

fnames = dir(fullfile(indir, 'Forcings_*'));
% info = ncinfo(fullfile(indir, fnames(1).name));

lon = ncread(fullfile(indir, fnames(1).name), 'lon');
lat = ncread(fullfile(indir, fnames(1).name), 'lat');
time = ncread(fullfile(indir, fnames(1).name), 'time');
ndays = length(fnames);
nt_per_day = length(time);
nlat = length(lat);
nlon = length(lon);

mask=ones(length(lon),length(lat));
mask = single(mask);

% Read in meteorological data for each day and combine
temperature = NaN(nlon, nlat, ndays*nt_per_day);
precipitation = NaN(nlon, nlat, ndays*nt_per_day);
pressure = NaN(nlon, nlat, ndays*nt_per_day);
shortwave = NaN(nlon, nlat, ndays*nt_per_day);
longwave = NaN(nlon, nlat, ndays*nt_per_day);
vp = NaN(nlon, nlat, ndays*nt_per_day);
wind = NaN(nlon, nlat, ndays*nt_per_day);
for d=1:ndays    
    t1 = nt_per_day*(d-1)+1;
    t2 = t1+nt_per_day-1;
    temperature(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'temperature');
    precipitation(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'precipitation');
    pressure(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'pressure');
    shortwave(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'shortwave');
    longwave(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'longwave');
    vp(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'vapor_pressure');
    wind(:,:,t1:t2) = ncread(fullfile(indir, fnames(d).name), 'wind_speed');
end

% Create NetCDF file
    
nccreate(outname,'time',...
    'Datatype','int32',...
    'Dimensions',{'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')

nccreate(outname,'lon',...
    'Datatype','double',...
    'Dimensions',{'lon',length(lon)},...
          'Format','netcdf4_classic')
      
nccreate(outname,'lat',...
    'Datatype','double',...
    'Dimensions',{'lat',length(lat)},...
          'Format','netcdf4_classic')    
     
nccreate(outname,'mask',...
    'Datatype','int32',...
    'Dimensions',{'lon',length(lon),'lat',length(lat)},...
          'Format','netcdf4_classic')
      
nccreate(outname,'prcp',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')      
      
nccreate(outname,'tas',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')       
      
nccreate(outname,'dswrf',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'dlwrf',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'pres',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'vp',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'wind',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   
      
% Write data to NetCDF file      
ncwrite(outname,'time',(1:ndays*nt_per_day)');
ncwrite(outname,'lon',lon);
ncwrite(outname,'lat',lat);
ncwrite(outname,'mask',mask);

ncwrite(outname,'prcp',precipitation);
ncwrite(outname,'tas',temperature);
ncwrite(outname,'dswrf',shortwave);
ncwrite(outname,'dlwrf',longwave);
ncwrite(outname,'pres',pressure);
ncwrite(outname,'vp',vp);
ncwrite(outname,'wind',wind);

% Write attributes
ncwriteatt(outname,...
    'time','units','hours since 1999-01-01');
ncwriteatt(outname,...
    'time','calendar','proleptic_gregorian');

ncwriteatt(outname,...
    'lon','standard_name','longitude');
ncwriteatt(outname,...
    'lon','long_name','longitude of grid cell center');
ncwriteatt(outname,...
    'lon','units','degrees_east');
ncwriteatt(outname,...
    'lon','axis','X');

ncwriteatt(outname,...
    'lat','standard_name','latitude');
ncwriteatt(outname,...
    'lat','long_name','latitude of grid cell center');
ncwriteatt(outname,...
    'lat','units','degrees_north');
ncwriteatt(outname,...
    'lat','axis','Y');

% ncwriteatt(outname,...
%     'mask','_FillValue',9.969209968386869e+36);
% ncwriteatt(outname,...
%     'mask','comment','NaN indicates cell is not active');
% ncwriteatt(outname,...
%     'mask','long_name','fraction of grid cell that is activedomain mask');
% ncwriteatt(outname,...
%     'mask','note','unitlessunitless');

% ncwriteatt(outname,...
%     'prcp','_FillValue','9.96921e+36f');
ncwriteatt(outname,...
    'prcp','long_name','PREC');
ncwriteatt(outname,...
    'prcp','column',int32(0));
ncwriteatt(outname,...
    'prcp','units','mm/step');
ncwriteatt(outname,...
    'prcp','description','PREC');

% ncwriteatt(outname,...
%     'tas','_FillValue','NaN');
ncwriteatt(outname,...
    'tas','long_name','AIR_TEMP');
ncwriteatt(outname,...
    'tas','column',int32(1));
ncwriteatt(outname,...
    'tas','units','C');
ncwriteatt(outname,...
    'tas','description','AIR_TEMP');

% ncwriteatt(outname,...
%     'dswrf','_FillValue','NaN');
ncwriteatt(outname,...
    'dswrf','long_name','SWDOWN');
ncwriteatt(outname,...
    'dswrf','column',int32(2));
ncwriteatt(outname,...
    'dswrf','units','S_/m2');
ncwriteatt(outname,...
    'dswrf','description','SWDOWN');

% ncwriteatt(outname,...
%     'dlwrf','_FillValue','NaN');
ncwriteatt(outname,...
    'dlwrf','long_name','LWDOWN');
ncwriteatt(outname,...
    'dlwrf','column',int32(3));
ncwriteatt(outname,...
    'dlwrf','units','S_/m2');
ncwriteatt(outname,...
    'dlwrf','description','LWDOWN');

% ncwriteatt(outname,...
%     'pres','_FillValue','NaN');
ncwriteatt(outname,...
    'pres','long_name','PRESSURE');
ncwriteatt(outname,...
    'pres','column',int32(5));
ncwriteatt(outname,...
    'pres','units','KPa');
ncwriteatt(outname,...
    'pres','description','PRESSURE');

% ncwriteatt(outname,...
%     'vp','_FillValue','NaN');
ncwriteatt(outname,...
    'vp','long_name','VP');
ncwriteatt(outname,...
    'vp','column',int32(6));
ncwriteatt(outname,...
    'vp','units','KPa');
ncwriteatt(outname,...
    'vp','description','VP');

% nccreate('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'Datatype', 'single', 'Dimensions', ...
%     {'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day}, ...
%     'Format', 'netcdf4_classic')
% ncwriteatt('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'column', 7)
% ncwriteatt('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'column2', single(7))
% ncwriteatt('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'column3', int32(7))

% ncwriteatt(outname,...
%     'wind','_FillValue','NaN');
ncwriteatt(outname,...
    'wind','long_name','WIND');
ncwriteatt(outname,...
    'wind','column',int32(7));
ncwriteatt(outname,...
    'wind','units','m/s');
ncwriteatt(outname,...
    'wind','description','WIND');

return
