% Write NetCDF forcing
% 
% Adapted from Dongyue's code 4/14/2020 JRS
% Resolution is hardcoded

function write_netcdf_forcing(temperature, precipitation, pressure, shortwave, longwave, vp, wind, info)

% save('/home/jschap/Documents/ESSD/bv2019_ucrb_run/write_netcdf_forcings_workspace.mat')
% load('/home/jschap/Documents/ESSD/bv2019_ucrb_run/write_netcdf_forcings_workspace.mat')

ndays = info.ndays;
nt_per_day = info.nt_per_day;
outname = info.outname;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% lon = min(lon):resolution:max(lon);
% lat = min(lat):resolution:max(lat);

mask = xyz2grid(info.lon, info.lat, ones(length(info.lon), 1));
% figure,plotraster(lon, lat, mask1, 'mask1')

% mask1(mask1==1) = 0;
% [lons, lats] = meshgrid(lon, lat);

% ncells = length(lon);
% for k=1:ncells
%     [i,j] = latlon2pix(R, lat(k), lon(k));
%     
% end

resolution = 0.0625;
R = makerefmat(min(info.lon), min(info.lat), resolution, resolution);
[lon, lat] = pixcenters(R, size(mask));

% mask=ones(length(lon),length(lat));
mask(isnan(mask)) = 0;
mask = single(mask);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Create NetCDF file
    
nccreate(outname,'time',...
    'Datatype','int32',...
    'Dimensions',{'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')

nccreate(outname,'lon',...
    'Datatype','double',...
    'Dimensions',{'lon',length(lon)},...
          'Format','netcdf4_classic')
      
nccreate(outname,'lat',...
    'Datatype','double',...
    'Dimensions',{'lat',length(lat)},...
          'Format','netcdf4_classic')    
     
nccreate(outname,'mask',...
    'Datatype','int32',...
    'Dimensions',{'lon',length(lon),'lat',length(lat)},...
          'Format','netcdf4_classic')
      
nccreate(outname,'prcp',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')      
      
nccreate(outname,'tas',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')       
      
nccreate(outname,'dswrf',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'dlwrf',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'pres',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'vp',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   

nccreate(outname,'wind',...
    'Datatype','single',...
    'Dimensions',{'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day},...
          'Format','netcdf4_classic')   
      
% Write data to NetCDF file      

% may need to start at 1. Not sure.
hours_per_step = 24/nt_per_day;
tt = (1:hours_per_step:ndays*24)'; % units are hours since start_time

ncwrite(outname,'time',tt);
ncwrite(outname,'lon',lon);
ncwrite(outname,'lat',lat);
ncwrite(outname,'mask',mask');

ncwrite(outname,'prcp',fliplr(precipitation));
ncwrite(outname,'tas',fliplr(temperature));
ncwrite(outname,'dswrf',fliplr(shortwave));
ncwrite(outname,'dlwrf',fliplr(longwave));
ncwrite(outname,'pres',fliplr(pressure));
ncwrite(outname,'vp',fliplr(vp));
ncwrite(outname,'wind',fliplr(wind));

% Write attributes

% specifies the time units in the forcing file metadata
% start_year = info.start_year;
start_year = info.year;

ncwriteatt(outname,...
    'time','units',['hours since ', num2str(start_year), '-01-01']);
ncwriteatt(outname,...
    'time','calendar','proleptic_gregorian');

ncwriteatt(outname,...
    'lon','standard_name','longitude');
ncwriteatt(outname,...
    'lon','long_name','longitude of grid cell center');
ncwriteatt(outname,...
    'lon','units','degrees_east');
ncwriteatt(outname,...
    'lon','axis','X');

ncwriteatt(outname,...
    'lat','standard_name','latitude');
ncwriteatt(outname,...
    'lat','long_name','latitude of grid cell center');
ncwriteatt(outname,...
    'lat','units','degrees_north');
ncwriteatt(outname,...
    'lat','axis','Y');

% ncwriteatt(outname,...
%     'mask','_FillValue',9.969209968386869e+36);
% ncwriteatt(outname,...
%     'mask','comment','NaN indicates cell is not active');
% ncwriteatt(outname,...
%     'mask','long_name','fraction of grid cell that is activedomain mask');
% ncwriteatt(outname,...
%     'mask','note','unitlessunitless');

% ncwriteatt(outname,...
%     'prcp','_FillValue','9.96921e+36f');
ncwriteatt(outname,...
    'prcp','long_name','PREC');
ncwriteatt(outname,...
    'prcp','column',int32(0));
ncwriteatt(outname,...
    'prcp','units','mm/step');
ncwriteatt(outname,...
    'prcp','description','PREC');

% ncwriteatt(outname,...
%     'tas','_FillValue','NaN');
ncwriteatt(outname,...
    'tas','long_name','AIR_TEMP');
ncwriteatt(outname,...
    'tas','column',int32(1));
ncwriteatt(outname,...
    'tas','units','C');
ncwriteatt(outname,...
    'tas','description','AIR_TEMP');

% ncwriteatt(outname,...
%     'dswrf','_FillValue','NaN');
ncwriteatt(outname,...
    'dswrf','long_name','SWDOWN');
ncwriteatt(outname,...
    'dswrf','column',int32(2));
ncwriteatt(outname,...
    'dswrf','units','S_/m2');
ncwriteatt(outname,...
    'dswrf','description','SWDOWN');

% ncwriteatt(outname,...
%     'dlwrf','_FillValue','NaN');
ncwriteatt(outname,...
    'dlwrf','long_name','LWDOWN');
ncwriteatt(outname,...
    'dlwrf','column',int32(3));
ncwriteatt(outname,...
    'dlwrf','units','S_/m2');
ncwriteatt(outname,...
    'dlwrf','description','LWDOWN');

% ncwriteatt(outname,...
%     'pres','_FillValue','NaN');
ncwriteatt(outname,...
    'pres','long_name','PRESSURE');
ncwriteatt(outname,...
    'pres','column',int32(5));
ncwriteatt(outname,...
    'pres','units','KPa');
ncwriteatt(outname,...
    'pres','description','PRESSURE');

% ncwriteatt(outname,...
%     'vp','_FillValue','NaN');
ncwriteatt(outname,...
    'vp','long_name','VP');
ncwriteatt(outname,...
    'vp','column',int32(6));
ncwriteatt(outname,...
    'vp','units','KPa');
ncwriteatt(outname,...
    'vp','description','VP');

% nccreate('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'Datatype', 'single', 'Dimensions', ...
%     {'lon',length(lon),'lat',length(lat),'time',ndays*nt_per_day}, ...
%     'Format', 'netcdf4_classic')
% ncwriteatt('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'column', 7)
% ncwriteatt('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'column2', single(7))
% ncwriteatt('/Volumes/HD4/SWOTDA/Data/Tuolumne/annoying.nc', 'dumbvar', ...
%     'column3', int32(7))

% ncwriteatt(outname,...
%     'wind','_FillValue','NaN');
ncwriteatt(outname,...
    'wind','long_name','WIND');
ncwriteatt(outname,...
    'wind','column',int32(7));
ncwriteatt(outname,...
    'wind','units','m/s');
ncwriteatt(outname,...
    'wind','description','WIND');

end